language: android
jdk:
- oraclejdk8
sudo: false
android:
  components:
  - extra-google-m2repository
  - extra-android-m2repository
  - platform-tools
  - tools
  - build-tools-26.0.1
  - android-26
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-19
before_install:
- echo $config_key | gpg --passphrase-fd 0 configuration.tar.gpg
- tar xvf configuration.tar
- chmod +x gradlew
script:
- "./gradlew clean lint test assembleDebug"
- if [[ "$TRAVIS_BRANCH" == "master" ]];then ./gradlew assembleRelease; fi
deploy:
  provider: releases
  api_key: $release_token
  file_glob: true
  file: "app/build/outputs/apk/releases/*-release.apk"
  skip_cleanup: true
  on:
    repo: ngengs/filkom-news-reader_application-android
    branch: master
